name: GitHub CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieves project from the git branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup node with specified version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Get yarn cache directory
        id: cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript check
        run: yarn tscheck

      - name: Run TSLint validation
        run: yarn tslint
      
      - name: Run tests
        run: yarn test